import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const SimpleHero = () => {
    const scrollToContact = () => {
        const contactSection = document.getElementById('scheduling');
        if (contactSection) {
            contactSection.scrollIntoView({ behavior: 'smooth' });
        }
    };
    return (_jsxs("section", { id: "hero", className: "relative min-h-screen flex items-center justify-center pt-20", children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-b from-amber-50 to-white dark:from-gray-900 dark:to-gray-950 -z-10" }), _jsxs("div", { className: "container mx-auto px-4 z-10 flex flex-col md:flex-row items-center justify-between", children: [_jsxs("div", { className: "md:w-1/2 text-center md:text-left mb-10 md:mb-0", children: [_jsxs("h1", { className: "text-4xl md:text-6xl font-serif font-bold mb-4 text-amber-700 dark:text-amber-500", children: [_jsx("span", { className: "block", children: "Abrar \u2013" }), _jsx("span", { className: "block mt-2", children: "Elite College Prep Coach" })] }), _jsx("p", { className: "text-xl md:text-2xl text-gray-700 dark:text-gray-300 font-light italic mb-8 max-w-xl", children: "Unleashing standout applications from standout students." }), _jsxs("div", { className: "flex flex-wrap justify-center md:justify-start gap-4", children: [_jsx("button", { onClick: scrollToContact, className: "px-8 py-3 rounded-full bg-amber-600 hover:bg-amber-500 text-white font-bold shadow-lg", children: "Book Free Consult" }), _jsx("button", { onClick: () => document.getElementById("application")?.scrollIntoView({ behavior: "smooth" }), className: "px-8 py-3 rounded-full bg-white dark:bg-gray-800 text-amber-600 dark:text-amber-400 font-bold shadow-lg", children: "Learn More" })] })] }), _jsx("div", { className: "md:w-1/2 flex justify-center md:justify-end", children: _jsx("div", { className: "relative w-64 h-64 md:w-80 md:h-80 rounded-full overflow-hidden border-4 border-amber-500 shadow-xl", children: _jsx("img", { src: "/images/profile.jpeg", alt: "Abrar", className: "w-full h-full object-cover" }) }) })] }), _jsxs("div", { className: "absolute bottom-10 left-1/2 transform -translate-x-1/2 flex flex-col items-center", children: [_jsx("span", { className: "text-sm text-gray-600 dark:text-gray-400 mb-2", children: "Scroll to explore" }), _jsx("svg", { className: "w-6 h-6 text-amber-500", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", xmlns: "http://www.w3.org/2000/svg", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M19 14l-7 7m0 0l-7-7m7 7V3" }) })] })] }));
};
export default SimpleHero;
