import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useRef } from 'react';
import { motion, useScroll, useTransform } from 'framer-motion';
import GlassmorphicCard from '../ui/GlassmorphicCard';
const VectorGraphic = () => {
    return (_jsx("div", { className: "w-full h-64 md:h-80 relative overflow-hidden", children: _jsxs("svg", { viewBox: "0 0 500 200", className: "w-full h-full", children: [_jsxs("defs", { children: [_jsxs("linearGradient", { id: "grad1", x1: "0%", y1: "0%", x2: "100%", y2: "0%", children: [_jsx("stop", { offset: "0%", stopColor: "#f59e0b", stopOpacity: "0.7" }), _jsx("stop", { offset: "100%", stopColor: "#d97706", stopOpacity: "0.7" })] }), _jsxs("linearGradient", { id: "grad2", x1: "0%", y1: "0%", x2: "100%", y2: "0%", children: [_jsx("stop", { offset: "0%", stopColor: "#fbbf24", stopOpacity: "0.5" }), _jsx("stop", { offset: "100%", stopColor: "#f59e0b", stopOpacity: "0.5" })] })] }), _jsx("path", { d: "M0,100 C150,180 350,0 500,100 L500,200 L0,200 Z", fill: "url(#grad1)", className: "animate-pulse-slow" }), _jsx("path", { d: "M0,100 C150,30 350,160 500,100 L500,200 L0,200 Z", fill: "url(#grad2)", className: "animate-pulse-slow animation-delay-2000" }), _jsx("circle", { cx: "100", cy: "80", r: "10", fill: "#fbbf24", className: "animate-float" }), _jsx("circle", { cx: "300", cy: "60", r: "8", fill: "#f59e0b", className: "animate-float animation-delay-2000" }), _jsx("circle", { cx: "400", cy: "90", r: "12", fill: "#d97706", className: "animate-float animation-delay-4000" }), _jsxs("g", { transform: "translate(150, 70)", className: "animate-float", children: [_jsx("rect", { x: "-15", y: "-15", width: "30", height: "30", rx: "5", fill: "#fbbf24", opacity: "0.8" }), _jsx("text", { x: "0", y: "5", textAnchor: "middle", fill: "white", fontSize: "16", children: "A+" })] }), _jsxs("g", { transform: "translate(250, 50)", className: "animate-float animation-delay-2000", children: [_jsx("circle", { cx: "0", cy: "0", r: "18", fill: "#f59e0b", opacity: "0.8" }), _jsx("text", { x: "0", y: "5", textAnchor: "middle", fill: "white", fontSize: "14", children: "SAT" })] }), _jsxs("g", { transform: "translate(350, 80)", className: "animate-float animation-delay-4000", children: [_jsx("polygon", { points: "0,-20 17,10 -17,10", fill: "#d97706", opacity: "0.8" }), _jsx("text", { x: "0", y: "5", textAnchor: "middle", fill: "white", fontSize: "12", children: "UC" })] })] }) }));
};
const ScrollAnimationSection = () => {
    const ref = useRef(null);
    const { scrollYProgress } = useScroll({
        target: ref,
        offset: ["start end", "end start"]
    });
    const opacity = useTransform(scrollYProgress, [0, 0.5, 1], [0, 1, 0]);
    const scale = useTransform(scrollYProgress, [0, 0.5, 1], [0.8, 1, 0.8]);
    const rotateZ = useTransform(scrollYProgress, [0, 0.5, 1], [-5, 0, 5]);
    return (_jsxs("div", { ref: ref, className: "py-20 relative overflow-hidden", children: [_jsxs("div", { className: "absolute inset-0 -z-10", children: [_jsx("div", { className: "absolute top-1/3 left-1/4 w-72 h-72 rounded-full bg-amber-400/10 blur-3xl animate-blob" }), _jsx("div", { className: "absolute bottom-1/4 right-1/3 w-64 h-64 rounded-full bg-amber-300/10 blur-3xl animate-blob animation-delay-4000" })] }), _jsx("div", { className: "container mx-auto px-4", children: _jsx(motion.div, { style: { opacity, scale, rotateZ }, className: "max-w-4xl mx-auto", children: _jsxs(GlassmorphicCard, { className: "text-center", children: [_jsx("h3", { className: "text-2xl md:text-3xl font-serif font-bold mb-6 bg-clip-text text-transparent bg-gradient-to-r from-amber-700 to-amber-500 dark:from-amber-500 dark:to-amber-300", children: "Elevate Your College Applications" }), _jsx(VectorGraphic, {}), _jsx("p", { className: "text-lg text-gray-700 dark:text-gray-300 mt-6", children: "With personalized guidance and proven strategies, we'll help you craft applications that truly stand out." })] }) }) })] }));
};
export default ScrollAnimationSection;
